### ISSUE TITLE
Does a rich_argparse example fit in the documentation anywhere?

### ISSUE THREAD

**Issue by peterjc** [fresh2dev/yapx#2]
I was pleased to find I could combine ``yapx`` with ``rich_argparse`` (from https://github.com/hamdanal/rich-argparse ) as follows:

```python
from rich_argparse import RichHelpFormatter
import yapx

def say_hello(name: str = 'World'):
    print(f"Hello {name}")

yapx.run(say_hello, formatter_class=RichHelpFormatter)
```

Sample output with the colours done via rich (cropped):

<img width="1194" alt="Screenshot 2024-11-05 at 19 29 50" src="https://github.com/user-attachments/assets/5d9a8784-435c-4a7c-bf2d-ff7f2ebb2eff">

Can you see where this might fit in the yapx documentation?

**Comment by peterjc** [comment]
A more complete example showing how to set the help text and metavar (and presumably any other property familiar to argparse users):

```python
from typing import Annotated
from rich_argparse import RichHelpFormatter
import yapx


def say_hello(
    name: Annotated[
        str, yapx.arg(help="Who or what to greet?", metavar="NAME")
    ] = "World",
):
    print(f"Hello {name}")


yapx.run(say_hello, formatter_class=RichHelpFormatter)
```

And the output (right cropped):

<img width="1231" alt="Screenshot 2024-11-05 at 20 39 21" src="https://github.com/user-attachments/assets/4e8c9199-83e7-4b59-b698-80cdf9170688">

**Comment by peterjc** [comment]
I've only just realized that this works "out of the box", if ``rich-argparse`` is installed, then it gets used automatically. Nice!

https://github.com/fresh2dev/yapx/blob/e814d71023fff3109c27d5397dcdc710980c7e6f/src/yapx/utils.py#L102

I guess that means there is no need for an example using ``RichHelpFormatter`` explicitly.

**Comment by fresh2dev** [comment]
You got it 👍 I'll make this capability more clear in the docs before I cut the next release.
